name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev tar graphviz autoconf libtool pkg-config
          pip install --upgrade pip setuptools wheel
          pip install "Cython<3.0.0" buildozer Kivy==2.3.0

      - name: Build with Buildozer
        env:
          # Litsenziyalarni avtomatik qabul qilish uchun muhit sozlamasi
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
        run: |
          # Bu yerda YES=1 va --auto-accept-licenses buyrug'i robotni litsenziyadan xatosiz o'tkazadi
          YES=1 buildozer -v android debug --auto-accept-licenses
